services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  scraper:
    build:
      context: ./scraper
    volumes:
      - ./scraper:/app
    depends_on:
      - kafka

  kafka_consumer:
    build:
      context: ./database
    volumes:
      - ./database:/app
    environment:
      DB_URL: "postgresql://m_mind:JvARh8lNgcKwExvuGxM4ew@big-data-project-6437.jxf.gcp-europe-west3.cockroachlabs.cloud:26257/trending?sslmode=verify-full"
      KAFKA_BROKER: "kafka:9092"
    depends_on:
      - kafka
    command: ["/app/wait-for-kafka.sh", "kafka", "9092", "python", "kafka_consumer.py"]