services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  scraper:
    build:
      context: ./scraper
    volumes:
      - ./scraper:/app
    depends_on:
      - kafka

  kafka_consumer:
    build:
      context: ./database
    volumes:
      - ./database:/app
    environment:
      DB_URL: "postgresql://admin:pass@cockroachdb:26257/videos"
      KAFKA_BROKER: "kafka:9092"
    depends_on:
      - kafka
      - cockroachdb
    networks:
      default:

  fill_categories:
    build:
      context: ./database
    depends_on:
      - cockroachdb
    networks:
      default:
        aliases:
          - fill_categories
    volumes:
      - ./scraper:/app/scraper  # Mount the scraper folder
    environment:
      - API_KEY=/app/scraper/api_key.txt

  cockroachdb:
    image: cockroachdb/cockroach:v22.2.7
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data

volumes:
  cockroach-data:
